#  Start the services 
---
  - hosts: database
    become: true
    tasks:
      - name: ensure mysql restarted
        service: name=mysql  state=restarted

  - hosts: webserver
    become: true
    tasks:
      - name: ensure webserver started
        service: name=apache2  state=started

  - hosts: loadbalancer
    become: true
    tasks:
      - name: ensure nginx started
        service: name=nginx  state=started


